version: '3'
services:
  sp-db: 
    image: postgres:13
    ports:
    - 5434:5432

    environment:
      POSTGRES_USER: mismaiel
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: secondProfit
    
    networks:
      - secondProfit
  

networks:
  secondProfit:
